### ISSUE TITLE
signIn: Cannot read property 'roles' of undefined

### ISSUE THREAD

**Issue by tochman** [Eth3rnit3/j-tockauth#1]
Awesome that you started to work on this. Just what I was looking for. We have used https://github.com/kylecorbelli/redux-token-auth in some projects, but find the package a bit overcomplicated. You seem to take a more straight forward approach. 

Anyway, I'm getting an error on line 268 in `index.js` when I authenticate: 

```
        this.roles = response ? response.data.roles : [];
```
Everything is okay on the back-end. I get a 200 response with the necessary authentication heades. But then I get: 
```
 TypeError: Cannot read property 'roles' of undefined
    at JtockAuth.setRoles (index.js:268)
    at index.js:84
```
When I debug this authenticating with my Rails6 API with DeviseTokenAuth, the `response` is :
```
{user: {
    courses: []
    email: "thomas@craftacademy.se"
    firstName: "Thomas"
    id: 11
    lastName: "Ochman"
    }
}
```

This is the way I use `signIn` 
```js
  const formSubmitHandler = () => {
    auth
      .signIn(formValues.email, formValues.password)
      .then(user => {
        console.table(user);
       // more code...
      })
      .catch(error => {
        console.error(error);
      }); 
  }
```
Params on the Rails side are okay:

```ruby
<ActionController::Parameters {"email"=>"thomas@craftacademy.se", "password"=>"password", "controller"=>"user_sessions", "action"=>"create", "user_session"=>{"email"=>"thomas@craftacademy.se", "password"=>"password"}} permitted: false>
```

Any thoughts? What am I missing? 

BTW, What are you using `roles` for? Is this specific for your own implementation or a generic attribute?

**Comment by Eth3rnit3** [comment]
Hello and thank you very much for your interest in the library.

I find this error strange because it implies that the response does not contain a `data` key. 

Indeed I added the `roles` key for personal use, I thought that it existed in many applications and that other people would probably use it

**Comment by Eth3rnit3** [comment]
I just released a small patch to use the roles conditionally (only if useRoles is passed as an option) so you can test the rest to see if it works on your side

**Comment by tochman** [comment]
Hi, thx for your response. The `data` key is not a problem. I reverted to an earlier commit of yours (0.7) and I was all good. I will try the newest version and let you know.

**Comment by Eth3rnit3** [comment]
All right, I look forward to your return!

On the other hand I don't know if you want to use j-tock-auth in production but I want to inform you that it doesn't respect all the security rules yet, if you read https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#security-risks it is rather advised to use httpOnly for token storage rather than localstorage as it is currently the case.

It is also possible to use localstorage but with a logic of encryption/decryption of the tokens.

I don't know where I'm headed yet.

**Comment by tochman** [comment]
The latest version works for me. Although I had to modify it slightly (for other reasons, not related to this issue). 

This is a prototype project and will undergo a lot of changes before we go to production, but I will have it in mind. Thx.

**Comment by Eth3rnit3** [comment]
Yes of course, thank you very much for your feedback.
